# Generated by Django 4.2.4 on 2023-08-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_projects',
            field=models.ManyToManyField(blank=True, related_name='employee_project', to='management.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='task_project', to='management.task'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='management.project'),
        ),
    ]
